modmap:
  - name: Global
    remap:
      Shift_L:
        alone_timeout_millis: 150
        alone: GRAVE
        held: Shift_L
      CTRL_R: ESC
      GRAVE: Tab
      Tab: ESC
      CapsLock: LEFTMETA
      Shift_R: LEFTMETA
      Muhenkan: Home
      Henkan: End
      KatakanaHiragana: End
