virtual_modifiers:
  - Ctrl_R
modmap:
  - name: Global
    remap:
      Shift_L:
        alone: GRAVE
        held: Shift_L
        free_hold: true
      CapsLock:
        alone: Esc
        held: LEFTMETA
        free_hold: true
      GRAVE: Alt_L
      Shift_R: LEFTMETA
      Muhenkan: Home
      Henkan: End
      KatakanaHiragana: End
keymap:
  - name: power
    exact_match: true
    remap:
      Ctrl-Alt-Shift-P: KEY_POWER
      Ctrl-Alt-Shift-R: KEY_RESTART

